[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "binomcikit"
version = "0.0.5"
authors = [
  { name="Vyasa R Rajeswaran", email="vyasarshi2308@gmail.com" },
  { name="Pranava BA", email="pranavabaascaran@gmail.com" }
]
description = "A Python package for calculating confidence intervals in statistical analysis using binomial distributions."
readme = "README.md"
long_description = { file = "README.md" } 
long_description_content_type = "text/markdown"
requires-python = ">=3.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/pranava-ba/binomcikit"
Issues = "https://github.com/pranava-ba/binomcikit"

[tool.hatch.build.targets.wheel]
packages = ["src/binomcikit"]
